### ISSUE TITLE
z drive ...

### ISSUE THREAD

**Issue by mathieuroche** [ne0YT/Linux-Subsystem-for-Windows_Seamless_windows_apps_on_Linux#1]
I may have missed something but I didn't see any explanation on how to get a z drive on the guest.

echo 'VBoxManage --nologo guestcontrol "win10" run --username admin --password RALFqxAbLDEdFfVdgXjPD2Yvk3uqjT4JG8V9yVhrkBAD8jpRjwh4dZmtMxpdHGAn --wait-stdout --exe "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -- powershell/arg0 "'**Z**:\\$1'"'

Thanks.

**Comment by ne0YT** [comment]
@mathieuroche hey there
I just updated the Readme:
https://github.com/ne0YT/Linux-Subsystem-for-Windows_Seamless_windows_apps_on_Linux

the relevant part begins with:
The VM needs to have guest-tools installed and you need to add the shared folder in virtualbox.
