### ISSUE TITLE
Window mode

### ISSUE THREAD

**Issue by cantalupo555** [ne0YT/Linux-Subsystem-for-Windows_Seamless_windows_apps_on_Linux#3]
When opening shortcut ".link" it runs the program inside the VM and not in windowed mode.

https://www.youtube.com/watch?v=DQ2FbkbNQP0

Would you be able to help?

**Comment by ne0YT** [comment]
you need to select seamless mode once in virtulabox. after that it will work. when you suspend the vm (by shutting down or using the "save windows" -"app") it will start back to "seamless mode" (also when shuting down the vm)

**Comment by cantalupo555** [comment]
> you need to select seamless mode once in virtulabox. after that it will work. when you suspend the vm (by shutting down or using the "save windows" -"app") it will start back to "seamless mode" (also when shuting down the vm)

Thank you
